name: FWThomas
version: 0.0.4-SNAPSHOT
api-version: "1.16"
description: SpigotMC plugin for increasing the maximum speed of minecarts
author: Shivs (OhMeMuffin)
main: it.forgottenworld.thomas.FWThomasPlugin
depend:
  - FWKotlinDeps
commands:
  thomas:
    description: Access FWThomas functions.
    usage: /thomas (while looking at a dispenser within 5 blocks)
    aliases: [ thomas ]
  dethomas:
    description: Access FWThomas functions.
    usage: /unthomas (while looking at a dispenser within 5 blocks)
    aliases: [ unthomas ]
permissions:
  thomas:
    description: Allows the player to use /thomas
    default: op
  unthomas:
    description: Allows the player to use /unthomas
    default: op